// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoIntegrador.Data.Context;

#nullable disable

namespace ProyectoIntegrador.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418125151_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.AsientoContable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AsientoOrigenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EjercicioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Glosa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AsientoOrigenId");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ClienteId", "EjercicioId", "Fecha");

                    b.ToTable("AsientosContables");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.CentroDeCosto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "Codigo")
                        .IsUnique();

                    b.ToTable("CentrosDeCosto");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonedaBase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreFantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoContribuyente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContadorId");

                    b.HasIndex("Rut")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.Comprobante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AsientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaContable")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ImportacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ImporteIva")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImporteNeto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutContraparte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TasaIva")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AsientoId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ImportacionId");

                    b.ToTable("Comprobantes");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.CuentaContable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("CuentaPadreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsImputable")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naturaleza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlanCuentasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CuentaPadreId");

                    b.HasIndex("PlanCuentasId", "Codigo")
                        .IsUnique();

                    b.ToTable("CuentasContables");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.EjercicioContable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("EjerciciosContables");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.Importacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaImportacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrosImportados")
                        .HasColumnType("int");

                    b.Property<int>("RegistrosRechazados")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Importaciones");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.LineaAsiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AsientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CentroCostoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CuentaContableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Debe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Haber")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImporteMonedaBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TipoCambio")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("CentroCostoId");

                    b.HasIndex("CuentaContableId");

                    b.HasIndex("AsientoId", "CuentaContableId");

                    b.ToTable("LineasAsiento");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0001-0001-0001-000000000001"),
                            Accion = "Crear",
                            Modulo = "Usuarios",
                            Nombre = "Crear Usuarios"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0001-0001-0001-000000000002"),
                            Accion = "Consultar",
                            Modulo = "Usuarios",
                            Nombre = "Consultar Usuarios"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0001-0001-0001-000000000003"),
                            Accion = "Editar",
                            Modulo = "Usuarios",
                            Nombre = "Editar Usuarios"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0001-0001-0001-000000000004"),
                            Accion = "Desactivar",
                            Modulo = "Usuarios",
                            Nombre = "Desactivar Usuarios"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0002-0001-0001-000000000001"),
                            Accion = "Crear",
                            Modulo = "Clientes",
                            Nombre = "Crear Clientes"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0002-0001-0001-000000000002"),
                            Accion = "Consultar",
                            Modulo = "Clientes",
                            Nombre = "Consultar Clientes"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0002-0001-0001-000000000003"),
                            Accion = "Editar",
                            Modulo = "Clientes",
                            Nombre = "Editar Clientes"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0002-0001-0001-000000000004"),
                            Accion = "Desactivar",
                            Modulo = "Clientes",
                            Nombre = "Desactivar Clientes"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0003-0001-0001-000000000001"),
                            Accion = "Crear",
                            Modulo = "Cuentas",
                            Nombre = "Crear Cuentas"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0003-0001-0001-000000000002"),
                            Accion = "Consultar",
                            Modulo = "Cuentas",
                            Nombre = "Consultar Cuentas"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0003-0001-0001-000000000003"),
                            Accion = "Editar",
                            Modulo = "Cuentas",
                            Nombre = "Editar Cuentas"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0003-0001-0001-000000000004"),
                            Accion = "Desactivar",
                            Modulo = "Cuentas",
                            Nombre = "Desactivar Cuentas"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0004-0001-0001-000000000001"),
                            Accion = "Crear",
                            Modulo = "Asientos",
                            Nombre = "Crear Asientos"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0004-0001-0001-000000000002"),
                            Accion = "Consultar",
                            Modulo = "Asientos",
                            Nombre = "Consultar Asientos"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0004-0001-0001-000000000003"),
                            Accion = "Revertir",
                            Modulo = "Asientos",
                            Nombre = "Revertir Asientos"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0005-0001-0001-000000000001"),
                            Accion = "Crear",
                            Modulo = "Comprobantes",
                            Nombre = "Crear Comprobantes"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0005-0001-0001-000000000002"),
                            Accion = "Consultar",
                            Modulo = "Comprobantes",
                            Nombre = "Consultar Comprobantes"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0005-0001-0001-000000000003"),
                            Accion = "Editar",
                            Modulo = "Comprobantes",
                            Nombre = "Editar Comprobantes"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0006-0001-0001-000000000001"),
                            Accion = "Crear",
                            Modulo = "Importaciones",
                            Nombre = "Crear Importaciones"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0006-0001-0001-000000000002"),
                            Accion = "Consultar",
                            Modulo = "Importaciones",
                            Nombre = "Consultar Importaciones"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0007-0001-0001-000000000001"),
                            Accion = "Consultar",
                            Modulo = "Reportes",
                            Nombre = "Consultar Reportes"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0007-0001-0001-000000000002"),
                            Accion = "Exportar",
                            Modulo = "Reportes",
                            Nombre = "Exportar Reportes"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0008-0001-0001-000000000001"),
                            Accion = "Crear",
                            Modulo = "Ejercicios",
                            Nombre = "Crear Ejercicios"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0008-0001-0001-000000000002"),
                            Accion = "Consultar",
                            Modulo = "Ejercicios",
                            Nombre = "Consultar Ejercicios"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0008-0001-0001-000000000003"),
                            Accion = "Editar",
                            Modulo = "Ejercicios",
                            Nombre = "Editar Ejercicios"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0008-0001-0001-000000000004"),
                            Accion = "Desactivar",
                            Modulo = "Ejercicios",
                            Nombre = "Desactivar Ejercicios"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0009-0001-0001-000000000001"),
                            Accion = "Crear",
                            Modulo = "CentrosCosto",
                            Nombre = "Crear Centros de Costo"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0009-0001-0001-000000000002"),
                            Accion = "Consultar",
                            Modulo = "CentrosCosto",
                            Nombre = "Consultar Centros de Costo"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0009-0001-0001-000000000003"),
                            Accion = "Editar",
                            Modulo = "CentrosCosto",
                            Nombre = "Editar Centros de Costo"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0009-0001-0001-000000000004"),
                            Accion = "Desactivar",
                            Modulo = "CentrosCosto",
                            Nombre = "Desactivar Centros de Costo"
                        });
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.PlanDeCuentas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("PlanesDeCuentas");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EsPredefinido")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            EsPredefinido = true,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            EsPredefinido = true,
                            Nombre = "Contador"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            EsPredefinido = true,
                            Nombre = "Auxiliar Contable"
                        });
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.RolPermiso", b =>
                {
                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("RolPermisos");

                    b.HasData(
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0001-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0001-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0001-0001-0001-000000000003")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0001-0001-0001-000000000004")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0002-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0002-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0002-0001-0001-000000000003")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0002-0001-0001-000000000004")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0003-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0003-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0003-0001-0001-000000000003")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0003-0001-0001-000000000004")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0004-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0004-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0004-0001-0001-000000000003")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0005-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0005-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0005-0001-0001-000000000003")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0006-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0006-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0007-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0007-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0008-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0008-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0008-0001-0001-000000000003")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0008-0001-0001-000000000004")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0009-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0009-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0009-0001-0001-000000000003")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            PermisoId = new Guid("b0000000-0009-0001-0001-000000000004")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0002-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0002-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0002-0001-0001-000000000003")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0002-0001-0001-000000000004")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0003-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0003-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0003-0001-0001-000000000003")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0003-0001-0001-000000000004")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0004-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0004-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0004-0001-0001-000000000003")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0005-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0005-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0005-0001-0001-000000000003")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0006-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0006-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0007-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0007-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0008-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0008-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0008-0001-0001-000000000003")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0008-0001-0001-000000000004")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0009-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0009-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0009-0001-0001-000000000003")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            PermisoId = new Guid("b0000000-0009-0001-0001-000000000004")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            PermisoId = new Guid("b0000000-0001-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            PermisoId = new Guid("b0000000-0002-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            PermisoId = new Guid("b0000000-0003-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            PermisoId = new Guid("b0000000-0004-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            PermisoId = new Guid("b0000000-0005-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            PermisoId = new Guid("b0000000-0006-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            PermisoId = new Guid("b0000000-0007-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            PermisoId = new Guid("b0000000-0008-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            PermisoId = new Guid("b0000000-0009-0001-0001-000000000002")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            PermisoId = new Guid("b0000000-0004-0001-0001-000000000001")
                        },
                        new
                        {
                            RolId = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            PermisoId = new Guid("b0000000-0005-0001-0001-000000000001")
                        });
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.SaldoCuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CuentaContableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DebeAcumulado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("EjercicioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("HaberAcumulado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CuentaContableId");

                    b.HasIndex("EjercicioId");

                    b.HasIndex("ClienteId", "CuentaContableId", "Periodo");

                    b.ToTable("SaldosCuenta");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.TipoDeCambio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuenteOrigen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("Moneda", "Fecha")
                        .IsUnique();

                    b.ToTable("TiposDeCambio");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.TokenRevocado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TokensRevocados");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ContadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProveedorAuth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContadorId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.AsientoContable", b =>
                {
                    b.HasOne("ProyectoIntegrador.Data.Entities.AsientoContable", "AsientoOrigen")
                        .WithMany("AsientosReversion")
                        .HasForeignKey("AsientoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProyectoIntegrador.Data.Entities.Cliente", "Cliente")
                        .WithMany("Asientos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoIntegrador.Data.Entities.EjercicioContable", "Ejercicio")
                        .WithMany("Asientos")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoIntegrador.Data.Entities.Usuario", "Usuario")
                        .WithMany("Asientos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsientoOrigen");

                    b.Navigation("Cliente");

                    b.Navigation("Ejercicio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.Auditoria", b =>
                {
                    b.HasOne("ProyectoIntegrador.Data.Entities.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.CentroDeCosto", b =>
                {
                    b.HasOne("ProyectoIntegrador.Data.Entities.Cliente", "Cliente")
                        .WithMany("CentrosDeCosto")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.Cliente", b =>
                {
                    b.HasOne("ProyectoIntegrador.Data.Entities.Usuario", "Contador")
                        .WithMany("Clientes")
                        .HasForeignKey("ContadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contador");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.Comprobante", b =>
                {
                    b.HasOne("ProyectoIntegrador.Data.Entities.AsientoContable", "Asiento")
                        .WithMany("Comprobantes")
                        .HasForeignKey("AsientoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProyectoIntegrador.Data.Entities.Cliente", "Cliente")
                        .WithMany("Comprobantes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoIntegrador.Data.Entities.Importacion", "Importacion")
                        .WithMany("Comprobantes")
                        .HasForeignKey("ImportacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asiento");

                    b.Navigation("Cliente");

                    b.Navigation("Importacion");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.CuentaContable", b =>
                {
                    b.HasOne("ProyectoIntegrador.Data.Entities.CuentaContable", "CuentaPadre")
                        .WithMany("CuentasHijas")
                        .HasForeignKey("CuentaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProyectoIntegrador.Data.Entities.PlanDeCuentas", "PlanDeCuentas")
                        .WithMany("CuentasContables")
                        .HasForeignKey("PlanCuentasId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CuentaPadre");

                    b.Navigation("PlanDeCuentas");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.EjercicioContable", b =>
                {
                    b.HasOne("ProyectoIntegrador.Data.Entities.Cliente", "Cliente")
                        .WithMany("Ejercicios")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.Importacion", b =>
                {
                    b.HasOne("ProyectoIntegrador.Data.Entities.Cliente", "Cliente")
                        .WithMany("Importaciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoIntegrador.Data.Entities.Usuario", "Usuario")
                        .WithMany("Importaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.LineaAsiento", b =>
                {
                    b.HasOne("ProyectoIntegrador.Data.Entities.AsientoContable", "Asiento")
                        .WithMany("LineasAsiento")
                        .HasForeignKey("AsientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoIntegrador.Data.Entities.CentroDeCosto", "CentroCosto")
                        .WithMany("LineasAsiento")
                        .HasForeignKey("CentroCostoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProyectoIntegrador.Data.Entities.CuentaContable", "CuentaContable")
                        .WithMany("LineasAsiento")
                        .HasForeignKey("CuentaContableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asiento");

                    b.Navigation("CentroCosto");

                    b.Navigation("CuentaContable");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.PlanDeCuentas", b =>
                {
                    b.HasOne("ProyectoIntegrador.Data.Entities.Cliente", "Cliente")
                        .WithOne("PlanDeCuentas")
                        .HasForeignKey("ProyectoIntegrador.Data.Entities.PlanDeCuentas", "ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.RolPermiso", b =>
                {
                    b.HasOne("ProyectoIntegrador.Data.Entities.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoIntegrador.Data.Entities.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.SaldoCuenta", b =>
                {
                    b.HasOne("ProyectoIntegrador.Data.Entities.Cliente", "Cliente")
                        .WithMany("SaldosCuenta")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoIntegrador.Data.Entities.CuentaContable", "CuentaContable")
                        .WithMany("SaldosCuenta")
                        .HasForeignKey("CuentaContableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoIntegrador.Data.Entities.EjercicioContable", "Ejercicio")
                        .WithMany("SaldosCuenta")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("CuentaContable");

                    b.Navigation("Ejercicio");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.TokenRevocado", b =>
                {
                    b.HasOne("ProyectoIntegrador.Data.Entities.Usuario", "Usuario")
                        .WithMany("TokensRevocados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.Usuario", b =>
                {
                    b.HasOne("ProyectoIntegrador.Data.Entities.Usuario", "Contador")
                        .WithMany("Auxiliares")
                        .HasForeignKey("ContadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProyectoIntegrador.Data.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contador");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.AsientoContable", b =>
                {
                    b.Navigation("AsientosReversion");

                    b.Navigation("Comprobantes");

                    b.Navigation("LineasAsiento");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.CentroDeCosto", b =>
                {
                    b.Navigation("LineasAsiento");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.Cliente", b =>
                {
                    b.Navigation("Asientos");

                    b.Navigation("CentrosDeCosto");

                    b.Navigation("Comprobantes");

                    b.Navigation("Ejercicios");

                    b.Navigation("Importaciones");

                    b.Navigation("PlanDeCuentas");

                    b.Navigation("SaldosCuenta");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.CuentaContable", b =>
                {
                    b.Navigation("CuentasHijas");

                    b.Navigation("LineasAsiento");

                    b.Navigation("SaldosCuenta");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.EjercicioContable", b =>
                {
                    b.Navigation("Asientos");

                    b.Navigation("SaldosCuenta");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.Importacion", b =>
                {
                    b.Navigation("Comprobantes");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.PlanDeCuentas", b =>
                {
                    b.Navigation("CuentasContables");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ProyectoIntegrador.Data.Entities.Usuario", b =>
                {
                    b.Navigation("Asientos");

                    b.Navigation("Auditorias");

                    b.Navigation("Auxiliares");

                    b.Navigation("Clientes");

                    b.Navigation("Importaciones");

                    b.Navigation("TokensRevocados");
                });
#pragma warning restore 612, 618
        }
    }
}
